pipeline {

    agent {
        docker {
            image 'python:2.7.16-slim'
        }
    }
    

    stages {
        stage('build') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling vote app'
                dir('vote'){
                    sh 'pip install -i requirements.xt'
                }
                
            }
        }
        stage('test') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Testing vote app'
                dir('vote'){
                    sh 'nosetests -v'
                }
            }
        }
    }
    post {
        always {
            echo "Piepline for vote application is completed"
        }
    }
}