pipeline {

    agent none
    

    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
		    args '--user root'
                }
            }
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
                
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
		    args '--user root'
                }
            }
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Testing vote app'
                dir('vote'){
		    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }

        stage("docker-package") {
            agent any
            when {
                changeset "**/vote/**"
		branch "master"
            }
            steps {
                echo "Packaging vote app with docker"
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                        def voteImage = docker.build("mydock21/vote:v${env.BUILD_ID}", "./vote")
                        voteImage.push("${env.BRANCH_MASTER}")
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Piepline for vote application is completed"
        }
    }
}
