pipeline {
    agent any
    
    agent {
        docker {
            image 'maven:3.6.1-jdk-8-alpine'
        }
    }

    stages {
        stage('build') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
                
            }
        }
        stage('test') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Testing worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('docker-package') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app using docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1', 'dockerlogin') {
                        def workerImage = docker.build("mydock21/worker:v${env.BUILD_ID}", "./worker")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Pipeline for worker application is completed"
        }
    }
}
